### ISSUE TITLE
Idea feature: Switching avatar after creation

### ISSUE THREAD

**Issue by arnaudWasappli** [insidegui/AnimojiStudio#7]
Issue:
- Found a way to save puppet differently than screen recording

**Comment by arnaudWasappli** [comment]
+ recording the screen save also the yellow frame when searching for face

**Comment by insidegui** [comment]
It looks like those are two different issues.

Regarding the first one, the way this app does the recording (using ReplayKit) enables unlimited recording times, but prevents changing the character later.

Regarding the second one, since we're recording the screen, that overlay is going to be shown. I don't see it as a big deal since you're going to want to remove that portion from the video anyway, what I could do is prevent the recording from starting until the capture is working (the yellow overlay is gone).

**Comment by insidegui** [comment]
I'm going to close this since the first idea is not feasible (the app relies heavily on screen recording and changing that would mean a complete rewrite). The second one is doable so I'm going to file a new issue for that.

Thanks!
